version: '3'

services:
  database:
    container_name: pitchain_db
    image: mysql
    environment:
      MYSQL_DATABASE: pitchain_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    networks:
      - pitchain-network
  redis:
    container_name: pitchain_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - pitchain-network
  app:
    container_name: pitchain_app
    depends_on:
      - database
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - pitchain-network
networks:
  pitchain-network:
