name: CI

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev]
    paths:
      - '**'

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: 1. checkout
      uses: actions/checkout@v4

    - name: 2. Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 3. Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: 4. Copy application-prod.yml
      env:
        YML: ${{ secrets.APPLICATION_PROD_YML }}
        YML_DIR: src/main/resources
        YML_NAME: application-prod.yml
      run: |
        mkdir -p $YML_DIR
        echo -n "$YML" | base64 --decode > $YML_DIR/$YML_NAME

    - name: 5. Copy application-test.yml
      env:
        YML: ${{ secrets.APPLICATION_TEST_YML }}
        YML_DIR: src/test/resources
        YML_NAME: application-test.yml
      run: |
        mkdir -p $YML_DIR
        echo -n "$YML" | base64 --decode > $YML_DIR/$YML_NAME

    - name: 6. Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: 7. Build with Gradle
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: ./gradlew clean build
